### ISSUE TITLE
rosinstall file error

### ISSUE THREAD

**Issue by MaxMSun** [bostoncleek/sawback#1]
Hi Boston,

I think there might be a typo in the rosinstall file, where the version of intera_common should be "release-5.3.0" instead of "v5.3.0".

Muchen

**Comment by bostoncleek** [comment]
Hey Muchen, 

[Here](https://github.com/RethinkRobotics/intera_common/releases) is the release I am using.  Did this give you an error when you used the rosinstall file? Are you using the sawback?

**Comment by MaxMSun** [comment]
No I was just playing around yesterday :)
Thanks for the release number!

**Comment by bostoncleek** [comment]
No worries. 

Let me know if you encounter any issues with this package or others.
